# Generated by Django 5.1.7 on 2025-04-21 14:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='sent_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
