# Generated by Django 5.1.7 on 2025-04-25 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songline', '0003_letter_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
