# Generated by Django 5.1.7 on 2025-04-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songline', '0004_letter_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='letter_images/'),
        ),
    ]
