# Generated by Django 5.1.7 on 2025-04-26 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songline', '0005_letter_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='letter',
            name='image',
        ),
    ]
