# Generated by Django 4.2.20 on 2025-05-08 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songline', '0010_remove_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='is_opened',
            field=models.BooleanField(default=False, verbose_name='是否已打开'),
        ),
        migrations.AddField(
            model_name='letter',
            name='opened_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='打开时间'),
        ),
    ]
