# Generated by Django 4.2.20 on 2025-05-16 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songline', '0016_userprofile_is_online_userprofile_last_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='login_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
