# Generated by Django 5.1.7 on 2025-04-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0002_letter_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='sent',
            field=models.BooleanField(default=False),
        ),
    ]
