# Generated by Django 5.1.7 on 2025-04-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0006_remove_letter_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='letter_images/'),
        ),
    ]
