# Generated by Django 5.1.7 on 2025-04-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0007_letter_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(help_text='1 - 7 表示周一到周日', verbose_name='星期几')),
                ('start', models.CharField(help_text='格式：HH:MM', max_length=5, verbose_name='开始时间')),
                ('end', models.CharField(help_text='格式：HH:MM', max_length=5, verbose_name='结束时间')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
            ],
        ),
    ]
