# Generated by Django 5.1.7 on 2025-04-27 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0009_todo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
