# Generated by Django 4.2.20 on 2025-05-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0011_letter_is_opened_letter_opened_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='last_opened_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='letter',
            name='opened_ips',
            field=models.JSONField(default=list),
        ),
    ]
