# Generated by Django 4.2.20 on 2025-05-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letters', '0014_coupleprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='view_password',
            field=models.CharField(default='LibertyIsland', max_length=100),
        ),
        migrations.DeleteModel(
            name='CoupleProfile',
        ),
    ]
